-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 20:03:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IGORA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IGORA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IGORA` DEFAULT CHARACTER SET utf8 ;
USE `IGORA` ;

-- -----------------------------------------------------
-- Table `IGORA`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IGORA`.`Clients` (
  `Client code` INT NOT NULL,
  `Full name` VARCHAR(45) NOT NULL,
  `Passport data` INT NOT NULL,
  `Birthday date` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` INT NOT NULL,
  PRIMARY KEY (`Client code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGORA`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IGORA`.`Staff` (
  `Staff code` INT NOT NULL,
  `Last login` TIME NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Full name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `Type of login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Staff code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGORA`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IGORA`.`Orders` (
  `ID` INT NOT NULL,
  `Service code` INT NOT NULL,
  `Client code` INT NOT NULL,
  `Time of orders` TIME NOT NULL,
  `Date of creation` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Rental time` TIME NOT NULL,
  `Date of closing` DATE NOT NULL,
  `Services` VARCHAR(45) NOT NULL,
  `Client code` INT NOT NULL,
  `Staff code` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Client code_idx` (`Client code` ASC) VISIBLE,
  INDEX `Staff code_idx` (`Staff code` ASC) VISIBLE,
  CONSTRAINT `Client code`
    FOREIGN KEY (`Client code`)
    REFERENCES `IGORA`.`Clients` (`Client code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Staff code`
    FOREIGN KEY (`Staff code`)
    REFERENCES `IGORA`.`Staff` (`Staff code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IGORA`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IGORA`.`Services` (
  `Cost per hour` INT NOT NULL,
  `Name of the service` VARCHAR(45) NOT NULL,
  `Service code` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
